# Generated by Django 2.2.19 on 2022-05-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220503_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
